# Generated by Django 2.2.6 on 2020-01-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=250)),
                ('passw', models.CharField(max_length=250)),
                ('dat', models.DateTimeField(max_length=50)),
                ('message', models.TextField(max_length=500)),
                ('part', models.CharField(max_length=250)),
                ('ent', models.CharField(max_length=250)),
                ('inv', models.CharField(max_length=250)),
            ],
        ),
    ]
