# Generated by Django 2.2.6 on 2020-01-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitedesvins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='dat',
            field=models.DateField(max_length=50),
        ),
    ]
