# Generated by Django 2.2.6 on 2020-01-05 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitedesvins', '0002_auto_20200104_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='ent',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='inv',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='part',
        ),
    ]
